import 'package:isar/isar.dart';

part 'inner_studio_models.g.dart';

@collection
class UnlockedSticker {
  Id id = Isar.autoIncrement;

  late String name;
  late String imagePath; // Stores the local path of the sticker image asset
  late DateTime unlockedAt;

  // Sticker type indicators:    
  // Used to distinguish between user-added stickers and system-generated stickers.
  // These flags help organise stickers when displaying them in the sticker book.
  bool isCustom = false;
  bool isMilestone = false;

  // Stores additional categories for filtering and organising stickers.
  List<String> tags = [];
}

@collection
class StudioStateData {
  // Unique identifier automatically generated by Isar database.
  Id id = Isar.autoIncrement;

  // Stores the current progress towards unlocking the next reward sticker.
  int currentProgressPoints = 0;

  // The required points needed before the next sticker can be unlocked.
  int currentTargetPoints = 100;

  // Tracks the current sticker index used for selecting reward sticker assets.
  int currentStickerIndex = 0;

  // Stores completed activity identifiers and their completion counts.
  // This allows the system to track repeated tool usage and milestone achievements.
  List<String> completedActivityKeys = [];
  List<int> completedActivityCounts = [];
}